//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SuRun.rc
//
#define IDS_USAGE                       1
#define IDS_ASKOK                       2
#define IDS_APPNAME                     3
#define IDS_NODESK                      4
#define IDS_SERVICE_NAME                5
#define IDS_ASKINSTALL                  6
#define IDS_UNINSTALLADMIN              7
#define IDS_INSTALLADMIN                8
#define IDS_LOGONFAILED                 9
#define IDS_NOADMIN                     10
#define IDS_NOSURUNNER                  11
#define IDS_ASKSURUNNER                 12
#define IDS_MENUSTR                     13
#define IDS_BUILTINADMIN                14
#define IDS_SURUNNER_OK                 15
#define IDS_SURUNNER_ERR                16
#define IDS_LOGOFFON                    17
#define IDS_SYSMENUEXT                  18
#define IDS_SURUNINST                   19
#define IDS_SURUNUNINST                 20
#define IDS_SURUNREPAIR                 21
#define IDS_UNINSTREBOOT                22
#define IDS_RUNFAILED                   23
#define IDS_INSTALLOK                   24
#define IDS_STARTMENUDIR                25
#define IDS_STARTMNUCFG                 26
#define IDS_ASKUNINST                   27
#define IDS_STARTMUNINST                28
#define IDS_GRPDESC                     29
#define IDS_ASKUSRINSTALL               30
#define IDS_DOMAINGROUPS                31
#define IDS_ADDFILETOLIST               31
#define IDS_DOMAINGROUPS2               32
#define IDS_DELUSER                     32
#define IDS_CANCEL                      33
#define IDS_NOADD2USERS                 34
#define IDS_NOREMADMINS                 35
#define IDS_ADMINSHELL                  36
#define IDS_NOSECLOGON                  37
#define IDS_NOADMIN2                    38
#define IDS_RUNRESTRICTED               39
#define IDS_SETUP1                      40
#define IDS_SETUP2                      41
#define IDS_SETUP3                      42
#define IDI_MAINICON                    100
#define IDD_LOGONDLG                    101
#define IDI_INSTALL                     101
#define IDI_SETUP                       102
#define IDI_HELP                        103
#define IDD_DIALOG1                     104
#define IDI_SHIELD                      104
#define IDI_SHIELD2                     105
#define IDI_SHIELD1                     106
#define IDD_SETUP                       107
#define IDD_CURUSRLOGON                 108
#define IDD_CURUSRACK                   109
#define IDD_SETUP_MAIN                  110
#define IDD_SETUP1                      111
#define IDD_SETUP2                      112
#define IDD_SETUP3                      113
#define IDD_SETUP4                      114
#define IDD_DIALOG2                     120
#define IDD_ICONHELP                    120
#define IDD_SELUSER                     121
#define IDI_LISTICON                    200
#define IDI_LISTICON1                   201
#define IDI_LISTICON2                   202
#define IDI_LISTICON3                   203
#define IDI_LISTICON5                   204
#define IDI_LISTICON4                   205
#define IDC_USER                        1000
#define IDC_DLGQUESTION                 1001
#define IDC_PASSWORD                    1002
#define IDC_DOMAIN                      1003
#define IDC_USERBITMAP                  1004
#define IDC_WHTBK                       1005
#define IDC_SECICON                     1006
#define IDC_RADIO1                      1007
#define IDC_RADIO2                      1008
#define IDC_RADIO3                      1009
#define IDC_ASKTIMEOUT                  1010
#define IDC_BLURDESKTOP                 1011
#define IDC_SAVEPW                      1012
#define IDC_HINT                        1016
#define IDC_HINT2                       1017
#define IDC_HINTBK                      1018
#define IDC_SECICON1                    1019
#define IDC_FRAME1                      1020
#define IDC_FRAME2                      1021
#define IDC_USRST                       1022
#define IDC_PWDST                       1023
#define IDC_ALWAYSOK                    1025
#define IDC_WHITELIST                   1026
#define IDC_SHELLEXECOK                 1026
#define IDC_DELETE                      1027
#define IDC_ALLOWTIME                   1028
#define IDC_ICONHELP                    1028
#define IDC_OWNERGROUP                  1029
#define IDC_DELUSER                     1029
#define IDC_SETENERGY                   1030
#define IDC_WINUPD4ALL                  1031
#define IDC_EXTOPT                      1032
#define IDC_WINUPDBOOT                  1033
#define IDC_SETUP_TAB                   1033
#define IDC_EXTOPT2                     1034
#define IDC_BUTTON1                     1034
#define IDC_ADDAPP                      1034
#define IDC_EDITAPP                     1035
#define IDC_CTRLASADMIN                 1036
#define IDC_ADDUSER                     1036
#define IDC_CMDASADMIN                  1037
#define IDC_EXPASADMIN                  1038
#define IDC_RESTARTADMIN                1039
#define IDC_STARTADMIN                  1040
#define IDC_RUNSETUP                    1041
#define IDC_RESTRICTED                  1042
#define IDC_EDIT1                       1045
#define IDC_USERLIST                    1046

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        122
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1047
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
