//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SuRun.rc
//
#define IDS_USAGE                       1
#define IDS_ASKOK                       2
#define IDS_APPNAME                     3
#define IDS_NODESK                      4
#define ID_APPLY                        4
#define IDS_SERVICE_NAME                5
#define IDS_ASKRUNAS                    6
#define IDS_UNINSTALLADMIN              7
#define IDS_INSTALLADMIN                8
#define IDS_LOGONFAILED                 9
#define IDS_NOADMIN                     10
#define IDS_NOSURUNNER                  11
#define IDS_ASKSURUNNER                 12
#define IDS_MENUSTR                     13
#define IDS_BUILTINADMIN                14
#define IDS_SURUNNER_OK                 15
#define IDS_SURUNNER_ERR                16
#define IDS_LOGOFFON                    17
#define IDS_SYSMENUEXT                  18
#define IDS_SURUNINST                   19
#define IDS_SURUNUNINST                 20
#define IDS_SURUNREPAIR                 21
#define IDS_CPLNAME                     22
#define IDS_RUNFAILED                   23
#define IDS_EMPTYPASS                   24
#define IDS_STARTMENUDIR                25
#define IDS_SURUNSTUCK                  26
#define IDS_SWITCHBACK                  27
#define IDS_APPOK                       28
#define IDS_GRPDESC                     29
#define IDS_ADDTOBLKLIST                30
#define IDS_DOMAINGROUPS                31
#define IDS_ADDFILETOLIST               31
#define IDS_DOMAINGROUPS2               32
#define IDS_DELUSER                     32
#define IDS_CANCEL                      33
#define IDS_NOADD2USERS                 34
#define IDS_NOREMADMINS                 35
#define IDS_ADMINSHELL                  36
#define IDS_SIMPLESETUP                 37
#define IDS_NOADMIN2                    38
#define IDS_RUNRESTRICTED               39
#define IDS_SETUP1                      40
#define IDS_SETUP2                      41
#define IDS_SETUP3                      42
#define IDS_SETUP4                      43
#define IDS_ASKAUTO                     44
#define IDS_STARTED                     47
#define IDS_ASKSURUNNER1                48
#define IDS_BUILTINADMIN1               49
#define IDS_NOADD2USERS1                50
#define IDS_SURUNNER_ERR1               51
#define IDS_ADDUNINST                   52
#define IDS_ADDAUTORUN                  53
#define IDS_ADDASSOC                    54
#define IDS_ADDCPL                      55
#define IDS_REMUNINST                   56
#define IDS_REMAUTORUN                  57
#define IDS_REMASSOC                    58
#define IDS_REMCPL                      59
#define IDS_DELFILE                     60
#define IDS_DELFILEBOOT                 61
#define IDS_COPYFILE                    63
#define IDS_DELSERVICE                  64
#define IDS_DELREG                      65
#define IDS_SR2ADMIN                    66
#define IDS_DELSURUNNERS                67
#define IDS_INSTFAILED                  68
#define IDS_CLOSE                       69
#define IDS_INSTSUCCESS                 70
#define IDS_INSTSUCCESS2                71
#define IDC_LOGOFF                      72
#define IDC_INSTALL                     73
#define IDS_STARTSVC                    74
#define IDS_INSTSVC                     75
#define IDC_UNINSTALL                   76
#define IDS_UNINSTFAILED                77
#define IDS_UNINSTSUCCESS               78
#define IDS_RUNAS                       79
#define IDS_WARNADMIN                   80
#define IDS_WARNADMIN2                  81
#define IDS_WARNADMIN3                  82
#define IDS_WARNADMIN4                  83
#define IDS_WARNADMIN5                  84
#define IDS_SHNAME1                     85
#define IDS_SHNAME2                     86
#define IDS_SHNAME3                     87
#define IDS_SHNAME4                     88
#define IDS_SHNAME5                     89
#define IDS_SHNAME6                     90
#define IDS_SHNAME7                     91
#define IDS_SHNAME8                     92
#define IDS_BEAUTIFIED                  93
#define IDS_PW4SETUP                    94
#define IDS_REBOOT                      95
#define IDS_INSTSUCCESS3                96
#define IDS_HIDESELF                    97
#define IDS_NOIMPORT                    98
#define IDS_NOEXPORT                    99
#define IDS_ASKSURUNNER2                45
#define IDS_ASKSURUNNER3                46
#define IDI_MAINICON                    100
#define IDD_LOGONDLG                    101
#define IDD_DIALOG1                     104
#define IDI_SHIELD                      104
#define IDI_SHIELD2                     105
#define IDI_SHIELD1                     106
#define IDD_SETUP                       107
#define IDD_CURUSRLOGON                 108
#define IDD_CURUSRACK                   109
#define IDD_SETUP_MAIN                  110
#define IDD_SETUP1                      111
#define IDD_SETUP2                      112
#define IDD_SETUP3                      113
#define IDD_SETUP4                      114
#define IDD_DIALOG2                     120
#define IDD_ICONHELP                    120
#define IDD_SELUSER                     121
#define IDD_UPDATE                      122
#define IDD_INSTALL                     123
#define IDI_NOADMIN                     123
#define IDD_INSTALL1                    124
#define IDD_UNINSTALL                   124
#define IDI_NOWINDOW                    124
#define IDD_INSTALL2                    125
#define IDI_ADMIN                       125
#define IDD_RUNASDLG                    125
#define IDD_APPOPTIONS                  126
#define IDI_ADMIN1                      127
#define IDI_SHADMIN                     127
#define IDD_BLKLST                      127
#define IDI_SRADMIN                     129
#define IDD_ADDTOBLKLST                 135
#define IDD_IMPORTSETTINGS              137
#define IDI_LISTICON                    200
#define IDI_LISTICON1                   201
#define IDI_LISTICON2                   202
#define IDI_LISTICON3                   203
#define IDI_LISTICON5                   204
#define IDI_LISTICON4                   205
#define IDI_LISTICON6                   206
#define IDI_LISTICON7                   207
#define IDC_USER                        1000
#define IDC_DLGQUESTION                 1001
#define IDC_PASSWORD                    1002
#define IDC_DOMAIN                      1003
#define IDC_USERBITMAP                  1004
#define IDC_WHTBK                       1005
#define IDC_SECICON                     1006
#define IDC_RADIO1                      1007
#define IDC_NOASK1                      1007
#define IDC_RADIO2                      1008
#define IDC_NOASK2                      1008
#define IDC_RADIO3                      1009
#define IDC_AUTO1                       1009
#define IDC_ASKTIMEOUT                  1010
#define IDC_AUTO2                       1010
#define IDC_BLURDESKTOP                 1011
#define IDC_AUTO3                       1011
#define IDC_SAVEPW                      1012
#define IDC_RESTRICT1                   1012
#define IDC_DORUNAS                     1013
#define IDC_RESTRICT2                   1013
#define IDC_FADEDESKTOP                 1014
#define IDC_NOASK3                      1015
#define IDC_HINT                        1016
#define IDC_HINT2                       1017
#define IDC_HINTBK                      1018
#define IDC_SECICON1                    1019
#define IDC_FRAME1                      1020
#define IDC_FRAME2                      1021
#define IDC_USRST                       1022
#define IDC_PWDST                       1023
#define IDC_ALWAYSOK                    1025
#define IDC_WHITELIST                   1026
#define IDC_SHELLEXECOK                 1026
#define IDC_DELETE                      1027
#define IDC_ALLOWTIME                   1028
#define IDC_ICONHELP                    1028
#define IDC_OWNERGROUP                  1029
#define IDC_DELUSER                     1029
#define IDC_SETENERGY                   1030
#define IDC_WINUPD4ALL                  1031
#define IDC_EXTOPT                      1032
#define IDC_WINUPDBOOT                  1033
#define IDC_SETUP_TAB                   1033
#define IDC_EXTOPT2                     1034
#define IDC_BUTTON1                     1034
#define IDC_ADDAPP                      1034
#define IDC_SELFILE                     1034
#define IDC_EDITAPP                     1035
#define IDC_EXTOPT3                     1035
#define IDC_CTRLASADMIN                 1036
#define IDC_ADDUSER                     1036
#define IDC_CMDASADMIN                  1037
#define IDC_EXPASADMIN                  1038
#define IDC_RESTARTADMIN                1039
#define IDC_STARTADMIN                  1040
#define IDC_RUNSETUP                    1041
#define IDC_RESTRICTED                  1042
#define IDC_FILENAME                    1045
#define IDC_USERLIST                    1046
#define IDC_USERNAME                    1047
#define IDC_ALLUSERS                    1048
#define IDC_SHEXHOOK                    1049
#define IDC_IATHOOK                     1050
#define IDC_SHOWTRAY                    1051
#define IDC_NOCONVADMIN                 1052
#define IDC_NOCONVUSER                  1053
#define IDC_RESTRICTNEW                 1054
#define IDC_NOSETUPNEW                  1055
#define IDC_KEEPREGISTRY                1055
#define IDC_DELSURUNNERS                1056
#define IDC_QUESTION                    1057
#define IDC_SR2ADMIN                    1058
#define IDC_INSTLOG                     1059
#define IDC_IMPORT                      1060
#define IDC_EXPORT                      1061
#define IDC_OWNGRPST                    1070
#define IDC_OPTNST                      1071
#define IDC_TRAYSHOWADMIN               1072
#define IDC_OWNGRPST2                   1072
#define IDC_KEEPREGST                   1072
#define IDC_TRAYBALLOON                 1073
#define IDC_STOREPASS                   1074
#define IDC_WARNADMIN                   1075
#define IDC_AUTOCANCEL                  1077
#define IDC_HIDESURUN                   1078
#define IDC_REQPW4SETUP                 1079
#define IDC_SIMPLESETUP                 1080
#define IDC_ASKPW                       1081
#define IDC_REQADMIN                    1084
#define IDC_BLACKLIST                   1085
#define IDC_NOEXPERT                    1087
#define IDC_EXPSURUNSETTINGS            1088
#define IDC_EXPBLACKLIST                1089
#define IDC_EXPUSRSETTINGS              1090
#define IDC_IMPSURUNSETTINGS            1091
#define IDC_IMPBLACKLIST                1092
#define IDC_IMPUSRSETTINGS              1093
#define IDC_NOUSESURUNNERS              1094
#define IDC_IMEXSTATIC                  1095
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        136
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1099
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
